In [2]:
import numpy as np

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(shape=(5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [12]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [13]:
arr2 = np.random.randint(0,100,10)

In [14]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [15]:
arr.max()

95

In [17]:
arr.argmax()

0

In [26]:
arr = arr.reshape((5,2
            ))

In [27]:
arr

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [30]:
arr[2,1]

87